### ISSUE TITLE
"Editor's copy" link in README leads to blank page

### ISSUE THREAD

**Issue by annevk** [bifurcation/expect-ct#15]
It seems you never push to gh-pages. Setting something up that would be reliably in sync with master would be good (or remove the link I suppose to avoid confusion).

**Comment by estark37** [comment]
Thanks; this draft has been moved to the http-extensions repo now (https://github.com/httpwg/http-extensions/blob/master/draft-ietf-httpbis-expect-ct.md) so I won't be updating this one anymore.
