### ISSUE TITLE
Header syntax

### ISSUE THREAD

**Issue by annevk** [bifurcation/expect-ct#17]
Every now and then @mikewest suggests all new (browser-minted?) headers should use JSON. If that's still a thing, we should probably not deviate here? On the other hand, if this header doesn't really require a new syntax parser, it might be okay too.

**Comment by mikewest** [comment]
I do suggest that. A lot. Unfortunately, I'm pretty much the only one who seems to care about it.

HTTP WG is in the process of inventing a syntax I like even less than JSON, but that group seems convinced it's the right way forward (https://tools.ietf.org/html/draft-ietf-httpbis-header-structure-00).

I haven't looked at Expect-CT's syntax, but if it's relying on the exact same parser as an existing header, that seems like a good argument for not rocking the boat.

**Comment by annevk** [comment]
Fair enough. Hopefully the HTTP WG creates a blocklist then for the existing headers and their respective parsers, so that all new headers are forced to use the same new syntax.
